format: "0.1"
name: green_crypt
validation: "./validator.cue"
jobs:
  cases:
    steps:
    - uri: fs/build
      method: deployContract
      args:
        connection:
          networkNameOrChainId: "testnet"
    jobs:
      case1:
        steps:
        - uri: fs/build
          method: setData
          args:
            address: "$cases.0.data"
            value: 100
        - uri: fs/build
          method: getData
          args:
            address: "$cases.0.data"
